name: FTP Auto Upload

on:
  push:
    branches:
      - main  # ajuste conforme a branch que você quer monitorar para as atualizações

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Conectando via FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        server: ${{ secrets.FTP_URL }}  # Chave configurada em Settings > Secrets
        username: ${{ secrets.FTP_USERNAME }}  # Chave configurada em Settings > Secrets
        password: ${{ secrets.FTP_PASSWORD }}  # Chave configurada em Settings > Secrets
        local-dir: ./  # Caminho local do seu repositório que você quer enviar
        remote-dir: ./ # Diretório remoto onde você quer enviar os arquivos
